[package]
name = "code"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8"
rand = "0.6"
